// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Query4.proto

package com.example.proto;

public final class Query4 {
  private Query4() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Query4RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Query4Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 pastYears = 1;</code>
     */
    int getPastYears();

    /**
     * <code>string type = 2;</code>
     */
    java.lang.String getType();
    /**
     * <code>string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string length = 3;</code>
     */
    java.lang.String getLength();
    /**
     * <code>string length = 3;</code>
     */
    com.google.protobuf.ByteString
        getLengthBytes();
  }
  /**
   * Protobuf type {@code Query4Request}
   */
  public  static final class Query4Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Query4Request)
      Query4RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Query4Request.newBuilder() to construct.
    private Query4Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Query4Request() {
      pastYears_ = 0;
      type_ = "";
      length_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Query4Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              pastYears_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              length_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.Query4.internal_static_Query4Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.Query4.internal_static_Query4Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.Query4.Query4Request.class, com.example.proto.Query4.Query4Request.Builder.class);
    }

    public static final int PASTYEARS_FIELD_NUMBER = 1;
    private int pastYears_;
    /**
     * <code>int32 pastYears = 1;</code>
     */
    public int getPastYears() {
      return pastYears_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LENGTH_FIELD_NUMBER = 3;
    private volatile java.lang.Object length_;
    /**
     * <code>string length = 3;</code>
     */
    public java.lang.String getLength() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        length_ = s;
        return s;
      }
    }
    /**
     * <code>string length = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLengthBytes() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        length_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pastYears_ != 0) {
        output.writeInt32(1, pastYears_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      if (!getLengthBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, length_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pastYears_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pastYears_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      if (!getLengthBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, length_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.Query4.Query4Request)) {
        return super.equals(obj);
      }
      com.example.proto.Query4.Query4Request other = (com.example.proto.Query4.Query4Request) obj;

      boolean result = true;
      result = result && (getPastYears()
          == other.getPastYears());
      result = result && getType()
          .equals(other.getType());
      result = result && getLength()
          .equals(other.getLength());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PASTYEARS_FIELD_NUMBER;
      hash = (53 * hash) + getPastYears();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.Query4.Query4Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query4.Query4Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query4.Query4Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query4.Query4Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query4.Query4Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query4.Query4Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query4.Query4Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query4.Query4Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query4.Query4Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.Query4.Query4Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query4.Query4Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query4.Query4Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.Query4.Query4Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Query4Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Query4Request)
        com.example.proto.Query4.Query4RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.Query4.internal_static_Query4Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.Query4.internal_static_Query4Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.Query4.Query4Request.class, com.example.proto.Query4.Query4Request.Builder.class);
      }

      // Construct using com.example.proto.Query4.Query4Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pastYears_ = 0;

        type_ = "";

        length_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.Query4.internal_static_Query4Request_descriptor;
      }

      @java.lang.Override
      public com.example.proto.Query4.Query4Request getDefaultInstanceForType() {
        return com.example.proto.Query4.Query4Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.Query4.Query4Request build() {
        com.example.proto.Query4.Query4Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.Query4.Query4Request buildPartial() {
        com.example.proto.Query4.Query4Request result = new com.example.proto.Query4.Query4Request(this);
        result.pastYears_ = pastYears_;
        result.type_ = type_;
        result.length_ = length_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.Query4.Query4Request) {
          return mergeFrom((com.example.proto.Query4.Query4Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.Query4.Query4Request other) {
        if (other == com.example.proto.Query4.Query4Request.getDefaultInstance()) return this;
        if (other.getPastYears() != 0) {
          setPastYears(other.getPastYears());
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getLength().isEmpty()) {
          length_ = other.length_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.Query4.Query4Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.Query4.Query4Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pastYears_ ;
      /**
       * <code>int32 pastYears = 1;</code>
       */
      public int getPastYears() {
        return pastYears_;
      }
      /**
       * <code>int32 pastYears = 1;</code>
       */
      public Builder setPastYears(int value) {
        
        pastYears_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pastYears = 1;</code>
       */
      public Builder clearPastYears() {
        
        pastYears_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object length_ = "";
      /**
       * <code>string length = 3;</code>
       */
      public java.lang.String getLength() {
        java.lang.Object ref = length_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          length_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string length = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLengthBytes() {
        java.lang.Object ref = length_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          length_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string length = 3;</code>
       */
      public Builder setLength(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string length = 3;</code>
       */
      public Builder clearLength() {
        
        length_ = getDefaultInstance().getLength();
        onChanged();
        return this;
      }
      /**
       * <code>string length = 3;</code>
       */
      public Builder setLengthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        length_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Query4Request)
    }

    // @@protoc_insertion_point(class_scope:Query4Request)
    private static final com.example.proto.Query4.Query4Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.Query4.Query4Request();
    }

    public static com.example.proto.Query4.Query4Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Query4Request>
        PARSER = new com.google.protobuf.AbstractParser<Query4Request>() {
      @java.lang.Override
      public Query4Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Query4Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Query4Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Query4Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.Query4.Query4Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Query4ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Query4Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Result4 result4 = 1;</code>
     */
    java.util.List<com.example.proto.Query4.Result4> 
        getResult4List();
    /**
     * <code>repeated .Result4 result4 = 1;</code>
     */
    com.example.proto.Query4.Result4 getResult4(int index);
    /**
     * <code>repeated .Result4 result4 = 1;</code>
     */
    int getResult4Count();
    /**
     * <code>repeated .Result4 result4 = 1;</code>
     */
    java.util.List<? extends com.example.proto.Query4.Result4OrBuilder> 
        getResult4OrBuilderList();
    /**
     * <code>repeated .Result4 result4 = 1;</code>
     */
    com.example.proto.Query4.Result4OrBuilder getResult4OrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Query4Response}
   */
  public  static final class Query4Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Query4Response)
      Query4ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Query4Response.newBuilder() to construct.
    private Query4Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Query4Response() {
      result4_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Query4Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                result4_ = new java.util.ArrayList<com.example.proto.Query4.Result4>();
                mutable_bitField0_ |= 0x00000001;
              }
              result4_.add(
                  input.readMessage(com.example.proto.Query4.Result4.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          result4_ = java.util.Collections.unmodifiableList(result4_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.Query4.internal_static_Query4Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.Query4.internal_static_Query4Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.Query4.Query4Response.class, com.example.proto.Query4.Query4Response.Builder.class);
    }

    public static final int RESULT4_FIELD_NUMBER = 1;
    private java.util.List<com.example.proto.Query4.Result4> result4_;
    /**
     * <code>repeated .Result4 result4 = 1;</code>
     */
    public java.util.List<com.example.proto.Query4.Result4> getResult4List() {
      return result4_;
    }
    /**
     * <code>repeated .Result4 result4 = 1;</code>
     */
    public java.util.List<? extends com.example.proto.Query4.Result4OrBuilder> 
        getResult4OrBuilderList() {
      return result4_;
    }
    /**
     * <code>repeated .Result4 result4 = 1;</code>
     */
    public int getResult4Count() {
      return result4_.size();
    }
    /**
     * <code>repeated .Result4 result4 = 1;</code>
     */
    public com.example.proto.Query4.Result4 getResult4(int index) {
      return result4_.get(index);
    }
    /**
     * <code>repeated .Result4 result4 = 1;</code>
     */
    public com.example.proto.Query4.Result4OrBuilder getResult4OrBuilder(
        int index) {
      return result4_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < result4_.size(); i++) {
        output.writeMessage(1, result4_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < result4_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, result4_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.Query4.Query4Response)) {
        return super.equals(obj);
      }
      com.example.proto.Query4.Query4Response other = (com.example.proto.Query4.Query4Response) obj;

      boolean result = true;
      result = result && getResult4List()
          .equals(other.getResult4List());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getResult4Count() > 0) {
        hash = (37 * hash) + RESULT4_FIELD_NUMBER;
        hash = (53 * hash) + getResult4List().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.Query4.Query4Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query4.Query4Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query4.Query4Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query4.Query4Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query4.Query4Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query4.Query4Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query4.Query4Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query4.Query4Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query4.Query4Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.Query4.Query4Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query4.Query4Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query4.Query4Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.Query4.Query4Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Query4Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Query4Response)
        com.example.proto.Query4.Query4ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.Query4.internal_static_Query4Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.Query4.internal_static_Query4Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.Query4.Query4Response.class, com.example.proto.Query4.Query4Response.Builder.class);
      }

      // Construct using com.example.proto.Query4.Query4Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResult4FieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (result4Builder_ == null) {
          result4_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          result4Builder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.Query4.internal_static_Query4Response_descriptor;
      }

      @java.lang.Override
      public com.example.proto.Query4.Query4Response getDefaultInstanceForType() {
        return com.example.proto.Query4.Query4Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.Query4.Query4Response build() {
        com.example.proto.Query4.Query4Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.Query4.Query4Response buildPartial() {
        com.example.proto.Query4.Query4Response result = new com.example.proto.Query4.Query4Response(this);
        int from_bitField0_ = bitField0_;
        if (result4Builder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            result4_ = java.util.Collections.unmodifiableList(result4_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.result4_ = result4_;
        } else {
          result.result4_ = result4Builder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.Query4.Query4Response) {
          return mergeFrom((com.example.proto.Query4.Query4Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.Query4.Query4Response other) {
        if (other == com.example.proto.Query4.Query4Response.getDefaultInstance()) return this;
        if (result4Builder_ == null) {
          if (!other.result4_.isEmpty()) {
            if (result4_.isEmpty()) {
              result4_ = other.result4_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResult4IsMutable();
              result4_.addAll(other.result4_);
            }
            onChanged();
          }
        } else {
          if (!other.result4_.isEmpty()) {
            if (result4Builder_.isEmpty()) {
              result4Builder_.dispose();
              result4Builder_ = null;
              result4_ = other.result4_;
              bitField0_ = (bitField0_ & ~0x00000001);
              result4Builder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResult4FieldBuilder() : null;
            } else {
              result4Builder_.addAllMessages(other.result4_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.Query4.Query4Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.Query4.Query4Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.proto.Query4.Result4> result4_ =
        java.util.Collections.emptyList();
      private void ensureResult4IsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          result4_ = new java.util.ArrayList<com.example.proto.Query4.Result4>(result4_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.proto.Query4.Result4, com.example.proto.Query4.Result4.Builder, com.example.proto.Query4.Result4OrBuilder> result4Builder_;

      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public java.util.List<com.example.proto.Query4.Result4> getResult4List() {
        if (result4Builder_ == null) {
          return java.util.Collections.unmodifiableList(result4_);
        } else {
          return result4Builder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public int getResult4Count() {
        if (result4Builder_ == null) {
          return result4_.size();
        } else {
          return result4Builder_.getCount();
        }
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public com.example.proto.Query4.Result4 getResult4(int index) {
        if (result4Builder_ == null) {
          return result4_.get(index);
        } else {
          return result4Builder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public Builder setResult4(
          int index, com.example.proto.Query4.Result4 value) {
        if (result4Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResult4IsMutable();
          result4_.set(index, value);
          onChanged();
        } else {
          result4Builder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public Builder setResult4(
          int index, com.example.proto.Query4.Result4.Builder builderForValue) {
        if (result4Builder_ == null) {
          ensureResult4IsMutable();
          result4_.set(index, builderForValue.build());
          onChanged();
        } else {
          result4Builder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public Builder addResult4(com.example.proto.Query4.Result4 value) {
        if (result4Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResult4IsMutable();
          result4_.add(value);
          onChanged();
        } else {
          result4Builder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public Builder addResult4(
          int index, com.example.proto.Query4.Result4 value) {
        if (result4Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResult4IsMutable();
          result4_.add(index, value);
          onChanged();
        } else {
          result4Builder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public Builder addResult4(
          com.example.proto.Query4.Result4.Builder builderForValue) {
        if (result4Builder_ == null) {
          ensureResult4IsMutable();
          result4_.add(builderForValue.build());
          onChanged();
        } else {
          result4Builder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public Builder addResult4(
          int index, com.example.proto.Query4.Result4.Builder builderForValue) {
        if (result4Builder_ == null) {
          ensureResult4IsMutable();
          result4_.add(index, builderForValue.build());
          onChanged();
        } else {
          result4Builder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public Builder addAllResult4(
          java.lang.Iterable<? extends com.example.proto.Query4.Result4> values) {
        if (result4Builder_ == null) {
          ensureResult4IsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, result4_);
          onChanged();
        } else {
          result4Builder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public Builder clearResult4() {
        if (result4Builder_ == null) {
          result4_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          result4Builder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public Builder removeResult4(int index) {
        if (result4Builder_ == null) {
          ensureResult4IsMutable();
          result4_.remove(index);
          onChanged();
        } else {
          result4Builder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public com.example.proto.Query4.Result4.Builder getResult4Builder(
          int index) {
        return getResult4FieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public com.example.proto.Query4.Result4OrBuilder getResult4OrBuilder(
          int index) {
        if (result4Builder_ == null) {
          return result4_.get(index);  } else {
          return result4Builder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public java.util.List<? extends com.example.proto.Query4.Result4OrBuilder> 
           getResult4OrBuilderList() {
        if (result4Builder_ != null) {
          return result4Builder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(result4_);
        }
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public com.example.proto.Query4.Result4.Builder addResult4Builder() {
        return getResult4FieldBuilder().addBuilder(
            com.example.proto.Query4.Result4.getDefaultInstance());
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public com.example.proto.Query4.Result4.Builder addResult4Builder(
          int index) {
        return getResult4FieldBuilder().addBuilder(
            index, com.example.proto.Query4.Result4.getDefaultInstance());
      }
      /**
       * <code>repeated .Result4 result4 = 1;</code>
       */
      public java.util.List<com.example.proto.Query4.Result4.Builder> 
           getResult4BuilderList() {
        return getResult4FieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.proto.Query4.Result4, com.example.proto.Query4.Result4.Builder, com.example.proto.Query4.Result4OrBuilder> 
          getResult4FieldBuilder() {
        if (result4Builder_ == null) {
          result4Builder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.proto.Query4.Result4, com.example.proto.Query4.Result4.Builder, com.example.proto.Query4.Result4OrBuilder>(
                  result4_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          result4_ = null;
        }
        return result4Builder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Query4Response)
    }

    // @@protoc_insertion_point(class_scope:Query4Response)
    private static final com.example.proto.Query4.Query4Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.Query4.Query4Response();
    }

    public static com.example.proto.Query4.Query4Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Query4Response>
        PARSER = new com.google.protobuf.AbstractParser<Query4Response>() {
      @java.lang.Override
      public Query4Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Query4Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Query4Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Query4Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.Query4.Query4Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Result4OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Result4)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string State = 1;</code>
     */
    java.lang.String getState();
    /**
     * <code>string State = 1;</code>
     */
    com.google.protobuf.ByteString
        getStateBytes();

    /**
     * <code>double GrowthRate = 2;</code>
     */
    double getGrowthRate();

    /**
     * <code>int32 pastYears = 3;</code>
     */
    int getPastYears();
  }
  /**
   * Protobuf type {@code Result4}
   */
  public  static final class Result4 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Result4)
      Result4OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Result4.newBuilder() to construct.
    private Result4(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Result4() {
      state_ = "";
      growthRate_ = 0D;
      pastYears_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Result4(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              state_ = s;
              break;
            }
            case 17: {

              growthRate_ = input.readDouble();
              break;
            }
            case 24: {

              pastYears_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.Query4.internal_static_Result4_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.Query4.internal_static_Result4_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.Query4.Result4.class, com.example.proto.Query4.Result4.Builder.class);
    }

    public static final int STATE_FIELD_NUMBER = 1;
    private volatile java.lang.Object state_;
    /**
     * <code>string State = 1;</code>
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        state_ = s;
        return s;
      }
    }
    /**
     * <code>string State = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROWTHRATE_FIELD_NUMBER = 2;
    private double growthRate_;
    /**
     * <code>double GrowthRate = 2;</code>
     */
    public double getGrowthRate() {
      return growthRate_;
    }

    public static final int PASTYEARS_FIELD_NUMBER = 3;
    private int pastYears_;
    /**
     * <code>int32 pastYears = 3;</code>
     */
    public int getPastYears() {
      return pastYears_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, state_);
      }
      if (growthRate_ != 0D) {
        output.writeDouble(2, growthRate_);
      }
      if (pastYears_ != 0) {
        output.writeInt32(3, pastYears_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, state_);
      }
      if (growthRate_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, growthRate_);
      }
      if (pastYears_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pastYears_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.Query4.Result4)) {
        return super.equals(obj);
      }
      com.example.proto.Query4.Result4 other = (com.example.proto.Query4.Result4) obj;

      boolean result = true;
      result = result && getState()
          .equals(other.getState());
      result = result && (
          java.lang.Double.doubleToLongBits(getGrowthRate())
          == java.lang.Double.doubleToLongBits(
              other.getGrowthRate()));
      result = result && (getPastYears()
          == other.getPastYears());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState().hashCode();
      hash = (37 * hash) + GROWTHRATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getGrowthRate()));
      hash = (37 * hash) + PASTYEARS_FIELD_NUMBER;
      hash = (53 * hash) + getPastYears();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.Query4.Result4 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query4.Result4 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query4.Result4 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query4.Result4 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query4.Result4 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query4.Result4 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query4.Result4 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query4.Result4 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query4.Result4 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.Query4.Result4 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query4.Result4 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query4.Result4 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.Query4.Result4 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Result4}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Result4)
        com.example.proto.Query4.Result4OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.Query4.internal_static_Result4_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.Query4.internal_static_Result4_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.Query4.Result4.class, com.example.proto.Query4.Result4.Builder.class);
      }

      // Construct using com.example.proto.Query4.Result4.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        state_ = "";

        growthRate_ = 0D;

        pastYears_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.Query4.internal_static_Result4_descriptor;
      }

      @java.lang.Override
      public com.example.proto.Query4.Result4 getDefaultInstanceForType() {
        return com.example.proto.Query4.Result4.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.Query4.Result4 build() {
        com.example.proto.Query4.Result4 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.Query4.Result4 buildPartial() {
        com.example.proto.Query4.Result4 result = new com.example.proto.Query4.Result4(this);
        result.state_ = state_;
        result.growthRate_ = growthRate_;
        result.pastYears_ = pastYears_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.Query4.Result4) {
          return mergeFrom((com.example.proto.Query4.Result4)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.Query4.Result4 other) {
        if (other == com.example.proto.Query4.Result4.getDefaultInstance()) return this;
        if (!other.getState().isEmpty()) {
          state_ = other.state_;
          onChanged();
        }
        if (other.getGrowthRate() != 0D) {
          setGrowthRate(other.getGrowthRate());
        }
        if (other.getPastYears() != 0) {
          setPastYears(other.getPastYears());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.Query4.Result4 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.Query4.Result4) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object state_ = "";
      /**
       * <code>string State = 1;</code>
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string State = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string State = 1;</code>
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string State = 1;</code>
       */
      public Builder clearState() {
        
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>string State = 1;</code>
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        state_ = value;
        onChanged();
        return this;
      }

      private double growthRate_ ;
      /**
       * <code>double GrowthRate = 2;</code>
       */
      public double getGrowthRate() {
        return growthRate_;
      }
      /**
       * <code>double GrowthRate = 2;</code>
       */
      public Builder setGrowthRate(double value) {
        
        growthRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double GrowthRate = 2;</code>
       */
      public Builder clearGrowthRate() {
        
        growthRate_ = 0D;
        onChanged();
        return this;
      }

      private int pastYears_ ;
      /**
       * <code>int32 pastYears = 3;</code>
       */
      public int getPastYears() {
        return pastYears_;
      }
      /**
       * <code>int32 pastYears = 3;</code>
       */
      public Builder setPastYears(int value) {
        
        pastYears_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pastYears = 3;</code>
       */
      public Builder clearPastYears() {
        
        pastYears_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Result4)
    }

    // @@protoc_insertion_point(class_scope:Result4)
    private static final com.example.proto.Query4.Result4 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.Query4.Result4();
    }

    public static com.example.proto.Query4.Result4 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Result4>
        PARSER = new com.google.protobuf.AbstractParser<Result4>() {
      @java.lang.Override
      public Result4 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Result4(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Result4> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Result4> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.Query4.Result4 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Query4Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Query4Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Query4Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Query4Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Result4_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Result4_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Query4.proto\"@\n\rQuery4Request\022\021\n\tpastY" +
      "ears\030\001 \001(\005\022\014\n\004type\030\002 \001(\t\022\016\n\006length\030\003 \001(\t" +
      "\"+\n\016Query4Response\022\031\n\007result4\030\001 \003(\0132\010.Re" +
      "sult4\"?\n\007Result4\022\r\n\005State\030\001 \001(\t\022\022\n\nGrowt" +
      "hRate\030\002 \001(\001\022\021\n\tpastYears\030\003 \001(\0052:\n\rQuery4" +
      "Service\022)\n\006Query4\022\016.Query4Request\032\017.Quer" +
      "y4ResponseB\023\n\021com.example.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Query4Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Query4Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Query4Request_descriptor,
        new java.lang.String[] { "PastYears", "Type", "Length", });
    internal_static_Query4Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Query4Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Query4Response_descriptor,
        new java.lang.String[] { "Result4", });
    internal_static_Result4_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Result4_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Result4_descriptor,
        new java.lang.String[] { "State", "GrowthRate", "PastYears", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
