// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Query5.proto

package com.example.proto;

public final class Query5 {
  private Query5() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Query5RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Query5Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string year = 1;</code>
     */
    java.lang.String getYear();
    /**
     * <code>string year = 1;</code>
     */
    com.google.protobuf.ByteString
        getYearBytes();

    /**
     * <code>string type = 2;</code>
     */
    java.lang.String getType();
    /**
     * <code>string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string length = 3;</code>
     */
    java.lang.String getLength();
    /**
     * <code>string length = 3;</code>
     */
    com.google.protobuf.ByteString
        getLengthBytes();

    /**
     * <code>string region = 4;</code>
     */
    java.lang.String getRegion();
    /**
     * <code>string region = 4;</code>
     */
    com.google.protobuf.ByteString
        getRegionBytes();
  }
  /**
   * Protobuf type {@code Query5Request}
   */
  public  static final class Query5Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Query5Request)
      Query5RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Query5Request.newBuilder() to construct.
    private Query5Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Query5Request() {
      year_ = "";
      type_ = "";
      length_ = "";
      region_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Query5Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              year_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              length_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              region_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.Query5.internal_static_Query5Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.Query5.internal_static_Query5Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.Query5.Query5Request.class, com.example.proto.Query5.Query5Request.Builder.class);
    }

    public static final int YEAR_FIELD_NUMBER = 1;
    private volatile java.lang.Object year_;
    /**
     * <code>string year = 1;</code>
     */
    public java.lang.String getYear() {
      java.lang.Object ref = year_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        year_ = s;
        return s;
      }
    }
    /**
     * <code>string year = 1;</code>
     */
    public com.google.protobuf.ByteString
        getYearBytes() {
      java.lang.Object ref = year_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        year_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LENGTH_FIELD_NUMBER = 3;
    private volatile java.lang.Object length_;
    /**
     * <code>string length = 3;</code>
     */
    public java.lang.String getLength() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        length_ = s;
        return s;
      }
    }
    /**
     * <code>string length = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLengthBytes() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        length_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGION_FIELD_NUMBER = 4;
    private volatile java.lang.Object region_;
    /**
     * <code>string region = 4;</code>
     */
    public java.lang.String getRegion() {
      java.lang.Object ref = region_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        region_ = s;
        return s;
      }
    }
    /**
     * <code>string region = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRegionBytes() {
      java.lang.Object ref = region_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        region_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getYearBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, year_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      if (!getLengthBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, length_);
      }
      if (!getRegionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, region_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getYearBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, year_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      if (!getLengthBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, length_);
      }
      if (!getRegionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, region_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.Query5.Query5Request)) {
        return super.equals(obj);
      }
      com.example.proto.Query5.Query5Request other = (com.example.proto.Query5.Query5Request) obj;

      boolean result = true;
      result = result && getYear()
          .equals(other.getYear());
      result = result && getType()
          .equals(other.getType());
      result = result && getLength()
          .equals(other.getLength());
      result = result && getRegion()
          .equals(other.getRegion());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength().hashCode();
      hash = (37 * hash) + REGION_FIELD_NUMBER;
      hash = (53 * hash) + getRegion().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.Query5.Query5Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query5.Query5Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query5.Query5Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query5.Query5Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query5.Query5Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query5.Query5Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query5.Query5Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query5.Query5Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query5.Query5Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.Query5.Query5Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query5.Query5Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query5.Query5Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.Query5.Query5Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Query5Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Query5Request)
        com.example.proto.Query5.Query5RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.Query5.internal_static_Query5Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.Query5.internal_static_Query5Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.Query5.Query5Request.class, com.example.proto.Query5.Query5Request.Builder.class);
      }

      // Construct using com.example.proto.Query5.Query5Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        year_ = "";

        type_ = "";

        length_ = "";

        region_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.Query5.internal_static_Query5Request_descriptor;
      }

      @java.lang.Override
      public com.example.proto.Query5.Query5Request getDefaultInstanceForType() {
        return com.example.proto.Query5.Query5Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.Query5.Query5Request build() {
        com.example.proto.Query5.Query5Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.Query5.Query5Request buildPartial() {
        com.example.proto.Query5.Query5Request result = new com.example.proto.Query5.Query5Request(this);
        result.year_ = year_;
        result.type_ = type_;
        result.length_ = length_;
        result.region_ = region_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.Query5.Query5Request) {
          return mergeFrom((com.example.proto.Query5.Query5Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.Query5.Query5Request other) {
        if (other == com.example.proto.Query5.Query5Request.getDefaultInstance()) return this;
        if (!other.getYear().isEmpty()) {
          year_ = other.year_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getLength().isEmpty()) {
          length_ = other.length_;
          onChanged();
        }
        if (!other.getRegion().isEmpty()) {
          region_ = other.region_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.Query5.Query5Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.Query5.Query5Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object year_ = "";
      /**
       * <code>string year = 1;</code>
       */
      public java.lang.String getYear() {
        java.lang.Object ref = year_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          year_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string year = 1;</code>
       */
      public com.google.protobuf.ByteString
          getYearBytes() {
        java.lang.Object ref = year_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          year_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string year = 1;</code>
       */
      public Builder setYear(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string year = 1;</code>
       */
      public Builder clearYear() {
        
        year_ = getDefaultInstance().getYear();
        onChanged();
        return this;
      }
      /**
       * <code>string year = 1;</code>
       */
      public Builder setYearBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        year_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object length_ = "";
      /**
       * <code>string length = 3;</code>
       */
      public java.lang.String getLength() {
        java.lang.Object ref = length_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          length_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string length = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLengthBytes() {
        java.lang.Object ref = length_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          length_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string length = 3;</code>
       */
      public Builder setLength(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string length = 3;</code>
       */
      public Builder clearLength() {
        
        length_ = getDefaultInstance().getLength();
        onChanged();
        return this;
      }
      /**
       * <code>string length = 3;</code>
       */
      public Builder setLengthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        length_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object region_ = "";
      /**
       * <code>string region = 4;</code>
       */
      public java.lang.String getRegion() {
        java.lang.Object ref = region_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          region_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string region = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRegionBytes() {
        java.lang.Object ref = region_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          region_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string region = 4;</code>
       */
      public Builder setRegion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        region_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string region = 4;</code>
       */
      public Builder clearRegion() {
        
        region_ = getDefaultInstance().getRegion();
        onChanged();
        return this;
      }
      /**
       * <code>string region = 4;</code>
       */
      public Builder setRegionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        region_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Query5Request)
    }

    // @@protoc_insertion_point(class_scope:Query5Request)
    private static final com.example.proto.Query5.Query5Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.Query5.Query5Request();
    }

    public static com.example.proto.Query5.Query5Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Query5Request>
        PARSER = new com.google.protobuf.AbstractParser<Query5Request>() {
      @java.lang.Override
      public Query5Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Query5Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Query5Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Query5Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.Query5.Query5Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Query5ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Query5Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Result5 result5 = 1;</code>
     */
    java.util.List<com.example.proto.Query5.Result5> 
        getResult5List();
    /**
     * <code>repeated .Result5 result5 = 1;</code>
     */
    com.example.proto.Query5.Result5 getResult5(int index);
    /**
     * <code>repeated .Result5 result5 = 1;</code>
     */
    int getResult5Count();
    /**
     * <code>repeated .Result5 result5 = 1;</code>
     */
    java.util.List<? extends com.example.proto.Query5.Result5OrBuilder> 
        getResult5OrBuilderList();
    /**
     * <code>repeated .Result5 result5 = 1;</code>
     */
    com.example.proto.Query5.Result5OrBuilder getResult5OrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Query5Response}
   */
  public  static final class Query5Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Query5Response)
      Query5ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Query5Response.newBuilder() to construct.
    private Query5Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Query5Response() {
      result5_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Query5Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                result5_ = new java.util.ArrayList<com.example.proto.Query5.Result5>();
                mutable_bitField0_ |= 0x00000001;
              }
              result5_.add(
                  input.readMessage(com.example.proto.Query5.Result5.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          result5_ = java.util.Collections.unmodifiableList(result5_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.Query5.internal_static_Query5Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.Query5.internal_static_Query5Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.Query5.Query5Response.class, com.example.proto.Query5.Query5Response.Builder.class);
    }

    public static final int RESULT5_FIELD_NUMBER = 1;
    private java.util.List<com.example.proto.Query5.Result5> result5_;
    /**
     * <code>repeated .Result5 result5 = 1;</code>
     */
    public java.util.List<com.example.proto.Query5.Result5> getResult5List() {
      return result5_;
    }
    /**
     * <code>repeated .Result5 result5 = 1;</code>
     */
    public java.util.List<? extends com.example.proto.Query5.Result5OrBuilder> 
        getResult5OrBuilderList() {
      return result5_;
    }
    /**
     * <code>repeated .Result5 result5 = 1;</code>
     */
    public int getResult5Count() {
      return result5_.size();
    }
    /**
     * <code>repeated .Result5 result5 = 1;</code>
     */
    public com.example.proto.Query5.Result5 getResult5(int index) {
      return result5_.get(index);
    }
    /**
     * <code>repeated .Result5 result5 = 1;</code>
     */
    public com.example.proto.Query5.Result5OrBuilder getResult5OrBuilder(
        int index) {
      return result5_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < result5_.size(); i++) {
        output.writeMessage(1, result5_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < result5_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, result5_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.Query5.Query5Response)) {
        return super.equals(obj);
      }
      com.example.proto.Query5.Query5Response other = (com.example.proto.Query5.Query5Response) obj;

      boolean result = true;
      result = result && getResult5List()
          .equals(other.getResult5List());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getResult5Count() > 0) {
        hash = (37 * hash) + RESULT5_FIELD_NUMBER;
        hash = (53 * hash) + getResult5List().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.Query5.Query5Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query5.Query5Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query5.Query5Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query5.Query5Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query5.Query5Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query5.Query5Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query5.Query5Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query5.Query5Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query5.Query5Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.Query5.Query5Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query5.Query5Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query5.Query5Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.Query5.Query5Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Query5Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Query5Response)
        com.example.proto.Query5.Query5ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.Query5.internal_static_Query5Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.Query5.internal_static_Query5Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.Query5.Query5Response.class, com.example.proto.Query5.Query5Response.Builder.class);
      }

      // Construct using com.example.proto.Query5.Query5Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResult5FieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (result5Builder_ == null) {
          result5_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          result5Builder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.Query5.internal_static_Query5Response_descriptor;
      }

      @java.lang.Override
      public com.example.proto.Query5.Query5Response getDefaultInstanceForType() {
        return com.example.proto.Query5.Query5Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.Query5.Query5Response build() {
        com.example.proto.Query5.Query5Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.Query5.Query5Response buildPartial() {
        com.example.proto.Query5.Query5Response result = new com.example.proto.Query5.Query5Response(this);
        int from_bitField0_ = bitField0_;
        if (result5Builder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            result5_ = java.util.Collections.unmodifiableList(result5_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.result5_ = result5_;
        } else {
          result.result5_ = result5Builder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.Query5.Query5Response) {
          return mergeFrom((com.example.proto.Query5.Query5Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.Query5.Query5Response other) {
        if (other == com.example.proto.Query5.Query5Response.getDefaultInstance()) return this;
        if (result5Builder_ == null) {
          if (!other.result5_.isEmpty()) {
            if (result5_.isEmpty()) {
              result5_ = other.result5_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResult5IsMutable();
              result5_.addAll(other.result5_);
            }
            onChanged();
          }
        } else {
          if (!other.result5_.isEmpty()) {
            if (result5Builder_.isEmpty()) {
              result5Builder_.dispose();
              result5Builder_ = null;
              result5_ = other.result5_;
              bitField0_ = (bitField0_ & ~0x00000001);
              result5Builder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResult5FieldBuilder() : null;
            } else {
              result5Builder_.addAllMessages(other.result5_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.Query5.Query5Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.Query5.Query5Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.proto.Query5.Result5> result5_ =
        java.util.Collections.emptyList();
      private void ensureResult5IsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          result5_ = new java.util.ArrayList<com.example.proto.Query5.Result5>(result5_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.proto.Query5.Result5, com.example.proto.Query5.Result5.Builder, com.example.proto.Query5.Result5OrBuilder> result5Builder_;

      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public java.util.List<com.example.proto.Query5.Result5> getResult5List() {
        if (result5Builder_ == null) {
          return java.util.Collections.unmodifiableList(result5_);
        } else {
          return result5Builder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public int getResult5Count() {
        if (result5Builder_ == null) {
          return result5_.size();
        } else {
          return result5Builder_.getCount();
        }
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public com.example.proto.Query5.Result5 getResult5(int index) {
        if (result5Builder_ == null) {
          return result5_.get(index);
        } else {
          return result5Builder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public Builder setResult5(
          int index, com.example.proto.Query5.Result5 value) {
        if (result5Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResult5IsMutable();
          result5_.set(index, value);
          onChanged();
        } else {
          result5Builder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public Builder setResult5(
          int index, com.example.proto.Query5.Result5.Builder builderForValue) {
        if (result5Builder_ == null) {
          ensureResult5IsMutable();
          result5_.set(index, builderForValue.build());
          onChanged();
        } else {
          result5Builder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public Builder addResult5(com.example.proto.Query5.Result5 value) {
        if (result5Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResult5IsMutable();
          result5_.add(value);
          onChanged();
        } else {
          result5Builder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public Builder addResult5(
          int index, com.example.proto.Query5.Result5 value) {
        if (result5Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResult5IsMutable();
          result5_.add(index, value);
          onChanged();
        } else {
          result5Builder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public Builder addResult5(
          com.example.proto.Query5.Result5.Builder builderForValue) {
        if (result5Builder_ == null) {
          ensureResult5IsMutable();
          result5_.add(builderForValue.build());
          onChanged();
        } else {
          result5Builder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public Builder addResult5(
          int index, com.example.proto.Query5.Result5.Builder builderForValue) {
        if (result5Builder_ == null) {
          ensureResult5IsMutable();
          result5_.add(index, builderForValue.build());
          onChanged();
        } else {
          result5Builder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public Builder addAllResult5(
          java.lang.Iterable<? extends com.example.proto.Query5.Result5> values) {
        if (result5Builder_ == null) {
          ensureResult5IsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, result5_);
          onChanged();
        } else {
          result5Builder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public Builder clearResult5() {
        if (result5Builder_ == null) {
          result5_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          result5Builder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public Builder removeResult5(int index) {
        if (result5Builder_ == null) {
          ensureResult5IsMutable();
          result5_.remove(index);
          onChanged();
        } else {
          result5Builder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public com.example.proto.Query5.Result5.Builder getResult5Builder(
          int index) {
        return getResult5FieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public com.example.proto.Query5.Result5OrBuilder getResult5OrBuilder(
          int index) {
        if (result5Builder_ == null) {
          return result5_.get(index);  } else {
          return result5Builder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public java.util.List<? extends com.example.proto.Query5.Result5OrBuilder> 
           getResult5OrBuilderList() {
        if (result5Builder_ != null) {
          return result5Builder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(result5_);
        }
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public com.example.proto.Query5.Result5.Builder addResult5Builder() {
        return getResult5FieldBuilder().addBuilder(
            com.example.proto.Query5.Result5.getDefaultInstance());
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public com.example.proto.Query5.Result5.Builder addResult5Builder(
          int index) {
        return getResult5FieldBuilder().addBuilder(
            index, com.example.proto.Query5.Result5.getDefaultInstance());
      }
      /**
       * <code>repeated .Result5 result5 = 1;</code>
       */
      public java.util.List<com.example.proto.Query5.Result5.Builder> 
           getResult5BuilderList() {
        return getResult5FieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.proto.Query5.Result5, com.example.proto.Query5.Result5.Builder, com.example.proto.Query5.Result5OrBuilder> 
          getResult5FieldBuilder() {
        if (result5Builder_ == null) {
          result5Builder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.proto.Query5.Result5, com.example.proto.Query5.Result5.Builder, com.example.proto.Query5.Result5OrBuilder>(
                  result5_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          result5_ = null;
        }
        return result5Builder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Query5Response)
    }

    // @@protoc_insertion_point(class_scope:Query5Response)
    private static final com.example.proto.Query5.Query5Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.Query5.Query5Response();
    }

    public static com.example.proto.Query5.Query5Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Query5Response>
        PARSER = new com.google.protobuf.AbstractParser<Query5Response>() {
      @java.lang.Override
      public Query5Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Query5Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Query5Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Query5Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.Query5.Query5Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Result5OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Result5)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string year = 1;</code>
     */
    java.lang.String getYear();
    /**
     * <code>string year = 1;</code>
     */
    com.google.protobuf.ByteString
        getYearBytes();

    /**
     * <code>string type = 2;</code>
     */
    java.lang.String getType();
    /**
     * <code>string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string length = 3;</code>
     */
    java.lang.String getLength();
    /**
     * <code>string length = 3;</code>
     */
    com.google.protobuf.ByteString
        getLengthBytes();

    /**
     * <code>string region = 4;</code>
     */
    java.lang.String getRegion();
    /**
     * <code>string region = 4;</code>
     */
    com.google.protobuf.ByteString
        getRegionBytes();

    /**
     * <code>double Expense = 5;</code>
     */
    double getExpense();
  }
  /**
   * Protobuf type {@code Result5}
   */
  public  static final class Result5 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Result5)
      Result5OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Result5.newBuilder() to construct.
    private Result5(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Result5() {
      year_ = "";
      type_ = "";
      length_ = "";
      region_ = "";
      expense_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Result5(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              year_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              length_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              region_ = s;
              break;
            }
            case 41: {

              expense_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.Query5.internal_static_Result5_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.Query5.internal_static_Result5_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.Query5.Result5.class, com.example.proto.Query5.Result5.Builder.class);
    }

    public static final int YEAR_FIELD_NUMBER = 1;
    private volatile java.lang.Object year_;
    /**
     * <code>string year = 1;</code>
     */
    public java.lang.String getYear() {
      java.lang.Object ref = year_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        year_ = s;
        return s;
      }
    }
    /**
     * <code>string year = 1;</code>
     */
    public com.google.protobuf.ByteString
        getYearBytes() {
      java.lang.Object ref = year_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        year_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LENGTH_FIELD_NUMBER = 3;
    private volatile java.lang.Object length_;
    /**
     * <code>string length = 3;</code>
     */
    public java.lang.String getLength() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        length_ = s;
        return s;
      }
    }
    /**
     * <code>string length = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLengthBytes() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        length_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGION_FIELD_NUMBER = 4;
    private volatile java.lang.Object region_;
    /**
     * <code>string region = 4;</code>
     */
    public java.lang.String getRegion() {
      java.lang.Object ref = region_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        region_ = s;
        return s;
      }
    }
    /**
     * <code>string region = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRegionBytes() {
      java.lang.Object ref = region_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        region_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPENSE_FIELD_NUMBER = 5;
    private double expense_;
    /**
     * <code>double Expense = 5;</code>
     */
    public double getExpense() {
      return expense_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getYearBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, year_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      if (!getLengthBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, length_);
      }
      if (!getRegionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, region_);
      }
      if (expense_ != 0D) {
        output.writeDouble(5, expense_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getYearBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, year_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      if (!getLengthBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, length_);
      }
      if (!getRegionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, region_);
      }
      if (expense_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, expense_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.Query5.Result5)) {
        return super.equals(obj);
      }
      com.example.proto.Query5.Result5 other = (com.example.proto.Query5.Result5) obj;

      boolean result = true;
      result = result && getYear()
          .equals(other.getYear());
      result = result && getType()
          .equals(other.getType());
      result = result && getLength()
          .equals(other.getLength());
      result = result && getRegion()
          .equals(other.getRegion());
      result = result && (
          java.lang.Double.doubleToLongBits(getExpense())
          == java.lang.Double.doubleToLongBits(
              other.getExpense()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength().hashCode();
      hash = (37 * hash) + REGION_FIELD_NUMBER;
      hash = (53 * hash) + getRegion().hashCode();
      hash = (37 * hash) + EXPENSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getExpense()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.Query5.Result5 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query5.Result5 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query5.Result5 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query5.Result5 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query5.Result5 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query5.Result5 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query5.Result5 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query5.Result5 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query5.Result5 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.Query5.Result5 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query5.Result5 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query5.Result5 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.Query5.Result5 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Result5}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Result5)
        com.example.proto.Query5.Result5OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.Query5.internal_static_Result5_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.Query5.internal_static_Result5_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.Query5.Result5.class, com.example.proto.Query5.Result5.Builder.class);
      }

      // Construct using com.example.proto.Query5.Result5.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        year_ = "";

        type_ = "";

        length_ = "";

        region_ = "";

        expense_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.Query5.internal_static_Result5_descriptor;
      }

      @java.lang.Override
      public com.example.proto.Query5.Result5 getDefaultInstanceForType() {
        return com.example.proto.Query5.Result5.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.Query5.Result5 build() {
        com.example.proto.Query5.Result5 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.Query5.Result5 buildPartial() {
        com.example.proto.Query5.Result5 result = new com.example.proto.Query5.Result5(this);
        result.year_ = year_;
        result.type_ = type_;
        result.length_ = length_;
        result.region_ = region_;
        result.expense_ = expense_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.Query5.Result5) {
          return mergeFrom((com.example.proto.Query5.Result5)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.Query5.Result5 other) {
        if (other == com.example.proto.Query5.Result5.getDefaultInstance()) return this;
        if (!other.getYear().isEmpty()) {
          year_ = other.year_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getLength().isEmpty()) {
          length_ = other.length_;
          onChanged();
        }
        if (!other.getRegion().isEmpty()) {
          region_ = other.region_;
          onChanged();
        }
        if (other.getExpense() != 0D) {
          setExpense(other.getExpense());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.Query5.Result5 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.Query5.Result5) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object year_ = "";
      /**
       * <code>string year = 1;</code>
       */
      public java.lang.String getYear() {
        java.lang.Object ref = year_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          year_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string year = 1;</code>
       */
      public com.google.protobuf.ByteString
          getYearBytes() {
        java.lang.Object ref = year_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          year_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string year = 1;</code>
       */
      public Builder setYear(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string year = 1;</code>
       */
      public Builder clearYear() {
        
        year_ = getDefaultInstance().getYear();
        onChanged();
        return this;
      }
      /**
       * <code>string year = 1;</code>
       */
      public Builder setYearBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        year_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object length_ = "";
      /**
       * <code>string length = 3;</code>
       */
      public java.lang.String getLength() {
        java.lang.Object ref = length_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          length_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string length = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLengthBytes() {
        java.lang.Object ref = length_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          length_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string length = 3;</code>
       */
      public Builder setLength(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string length = 3;</code>
       */
      public Builder clearLength() {
        
        length_ = getDefaultInstance().getLength();
        onChanged();
        return this;
      }
      /**
       * <code>string length = 3;</code>
       */
      public Builder setLengthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        length_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object region_ = "";
      /**
       * <code>string region = 4;</code>
       */
      public java.lang.String getRegion() {
        java.lang.Object ref = region_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          region_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string region = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRegionBytes() {
        java.lang.Object ref = region_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          region_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string region = 4;</code>
       */
      public Builder setRegion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        region_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string region = 4;</code>
       */
      public Builder clearRegion() {
        
        region_ = getDefaultInstance().getRegion();
        onChanged();
        return this;
      }
      /**
       * <code>string region = 4;</code>
       */
      public Builder setRegionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        region_ = value;
        onChanged();
        return this;
      }

      private double expense_ ;
      /**
       * <code>double Expense = 5;</code>
       */
      public double getExpense() {
        return expense_;
      }
      /**
       * <code>double Expense = 5;</code>
       */
      public Builder setExpense(double value) {
        
        expense_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double Expense = 5;</code>
       */
      public Builder clearExpense() {
        
        expense_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Result5)
    }

    // @@protoc_insertion_point(class_scope:Result5)
    private static final com.example.proto.Query5.Result5 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.Query5.Result5();
    }

    public static com.example.proto.Query5.Result5 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Result5>
        PARSER = new com.google.protobuf.AbstractParser<Result5>() {
      @java.lang.Override
      public Result5 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Result5(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Result5> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Result5> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.Query5.Result5 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Query5Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Query5Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Query5Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Query5Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Result5_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Result5_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Query5.proto\"K\n\rQuery5Request\022\014\n\004year\030" +
      "\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\016\n\006length\030\003 \001(\t\022\016\n\006r" +
      "egion\030\004 \001(\t\"+\n\016Query5Response\022\031\n\007result5" +
      "\030\001 \003(\0132\010.Result5\"V\n\007Result5\022\014\n\004year\030\001 \001(" +
      "\t\022\014\n\004type\030\002 \001(\t\022\016\n\006length\030\003 \001(\t\022\016\n\006regio" +
      "n\030\004 \001(\t\022\017\n\007Expense\030\005 \001(\0012:\n\rQuery5Servic" +
      "e\022)\n\006Query5\022\016.Query5Request\032\017.Query5Resp" +
      "onseB\023\n\021com.example.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Query5Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Query5Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Query5Request_descriptor,
        new java.lang.String[] { "Year", "Type", "Length", "Region", });
    internal_static_Query5Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Query5Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Query5Response_descriptor,
        new java.lang.String[] { "Result5", });
    internal_static_Result5_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Result5_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Result5_descriptor,
        new java.lang.String[] { "Year", "Type", "Length", "Region", "Expense", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
