// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Query2.proto

package com.example.proto;

public final class Query2 {
  private Query2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Query2RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Query2Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string year = 1;</code>
     */
    java.lang.String getYear();
    /**
     * <code>string year = 1;</code>
     */
    com.google.protobuf.ByteString
        getYearBytes();

    /**
     * <code>string type = 2;</code>
     */
    java.lang.String getType();
    /**
     * <code>string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string length = 3;</code>
     */
    java.lang.String getLength();
    /**
     * <code>string length = 3;</code>
     */
    com.google.protobuf.ByteString
        getLengthBytes();
  }
  /**
   * Protobuf type {@code Query2Request}
   */
  public  static final class Query2Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Query2Request)
      Query2RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Query2Request.newBuilder() to construct.
    private Query2Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Query2Request() {
      year_ = "";
      type_ = "";
      length_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Query2Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              year_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              length_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.Query2.internal_static_Query2Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.Query2.internal_static_Query2Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.Query2.Query2Request.class, com.example.proto.Query2.Query2Request.Builder.class);
    }

    public static final int YEAR_FIELD_NUMBER = 1;
    private volatile java.lang.Object year_;
    /**
     * <code>string year = 1;</code>
     */
    public java.lang.String getYear() {
      java.lang.Object ref = year_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        year_ = s;
        return s;
      }
    }
    /**
     * <code>string year = 1;</code>
     */
    public com.google.protobuf.ByteString
        getYearBytes() {
      java.lang.Object ref = year_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        year_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LENGTH_FIELD_NUMBER = 3;
    private volatile java.lang.Object length_;
    /**
     * <code>string length = 3;</code>
     */
    public java.lang.String getLength() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        length_ = s;
        return s;
      }
    }
    /**
     * <code>string length = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLengthBytes() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        length_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getYearBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, year_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      if (!getLengthBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, length_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getYearBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, year_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      if (!getLengthBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, length_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.Query2.Query2Request)) {
        return super.equals(obj);
      }
      com.example.proto.Query2.Query2Request other = (com.example.proto.Query2.Query2Request) obj;

      boolean result = true;
      result = result && getYear()
          .equals(other.getYear());
      result = result && getType()
          .equals(other.getType());
      result = result && getLength()
          .equals(other.getLength());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.Query2.Query2Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query2.Query2Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query2.Query2Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query2.Query2Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query2.Query2Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query2.Query2Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query2.Query2Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query2.Query2Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query2.Query2Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.Query2.Query2Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query2.Query2Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query2.Query2Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.Query2.Query2Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Query2Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Query2Request)
        com.example.proto.Query2.Query2RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.Query2.internal_static_Query2Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.Query2.internal_static_Query2Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.Query2.Query2Request.class, com.example.proto.Query2.Query2Request.Builder.class);
      }

      // Construct using com.example.proto.Query2.Query2Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        year_ = "";

        type_ = "";

        length_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.Query2.internal_static_Query2Request_descriptor;
      }

      @java.lang.Override
      public com.example.proto.Query2.Query2Request getDefaultInstanceForType() {
        return com.example.proto.Query2.Query2Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.Query2.Query2Request build() {
        com.example.proto.Query2.Query2Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.Query2.Query2Request buildPartial() {
        com.example.proto.Query2.Query2Request result = new com.example.proto.Query2.Query2Request(this);
        result.year_ = year_;
        result.type_ = type_;
        result.length_ = length_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.Query2.Query2Request) {
          return mergeFrom((com.example.proto.Query2.Query2Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.Query2.Query2Request other) {
        if (other == com.example.proto.Query2.Query2Request.getDefaultInstance()) return this;
        if (!other.getYear().isEmpty()) {
          year_ = other.year_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getLength().isEmpty()) {
          length_ = other.length_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.Query2.Query2Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.Query2.Query2Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object year_ = "";
      /**
       * <code>string year = 1;</code>
       */
      public java.lang.String getYear() {
        java.lang.Object ref = year_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          year_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string year = 1;</code>
       */
      public com.google.protobuf.ByteString
          getYearBytes() {
        java.lang.Object ref = year_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          year_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string year = 1;</code>
       */
      public Builder setYear(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string year = 1;</code>
       */
      public Builder clearYear() {
        
        year_ = getDefaultInstance().getYear();
        onChanged();
        return this;
      }
      /**
       * <code>string year = 1;</code>
       */
      public Builder setYearBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        year_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object length_ = "";
      /**
       * <code>string length = 3;</code>
       */
      public java.lang.String getLength() {
        java.lang.Object ref = length_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          length_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string length = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLengthBytes() {
        java.lang.Object ref = length_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          length_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string length = 3;</code>
       */
      public Builder setLength(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string length = 3;</code>
       */
      public Builder clearLength() {
        
        length_ = getDefaultInstance().getLength();
        onChanged();
        return this;
      }
      /**
       * <code>string length = 3;</code>
       */
      public Builder setLengthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        length_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Query2Request)
    }

    // @@protoc_insertion_point(class_scope:Query2Request)
    private static final com.example.proto.Query2.Query2Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.Query2.Query2Request();
    }

    public static com.example.proto.Query2.Query2Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Query2Request>
        PARSER = new com.google.protobuf.AbstractParser<Query2Request>() {
      @java.lang.Override
      public Query2Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Query2Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Query2Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Query2Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.Query2.Query2Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Query2ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Query2Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Result2 result2 = 1;</code>
     */
    java.util.List<com.example.proto.Query2.Result2> 
        getResult2List();
    /**
     * <code>repeated .Result2 result2 = 1;</code>
     */
    com.example.proto.Query2.Result2 getResult2(int index);
    /**
     * <code>repeated .Result2 result2 = 1;</code>
     */
    int getResult2Count();
    /**
     * <code>repeated .Result2 result2 = 1;</code>
     */
    java.util.List<? extends com.example.proto.Query2.Result2OrBuilder> 
        getResult2OrBuilderList();
    /**
     * <code>repeated .Result2 result2 = 1;</code>
     */
    com.example.proto.Query2.Result2OrBuilder getResult2OrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Query2Response}
   */
  public  static final class Query2Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Query2Response)
      Query2ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Query2Response.newBuilder() to construct.
    private Query2Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Query2Response() {
      result2_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Query2Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                result2_ = new java.util.ArrayList<com.example.proto.Query2.Result2>();
                mutable_bitField0_ |= 0x00000001;
              }
              result2_.add(
                  input.readMessage(com.example.proto.Query2.Result2.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          result2_ = java.util.Collections.unmodifiableList(result2_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.Query2.internal_static_Query2Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.Query2.internal_static_Query2Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.Query2.Query2Response.class, com.example.proto.Query2.Query2Response.Builder.class);
    }

    public static final int RESULT2_FIELD_NUMBER = 1;
    private java.util.List<com.example.proto.Query2.Result2> result2_;
    /**
     * <code>repeated .Result2 result2 = 1;</code>
     */
    public java.util.List<com.example.proto.Query2.Result2> getResult2List() {
      return result2_;
    }
    /**
     * <code>repeated .Result2 result2 = 1;</code>
     */
    public java.util.List<? extends com.example.proto.Query2.Result2OrBuilder> 
        getResult2OrBuilderList() {
      return result2_;
    }
    /**
     * <code>repeated .Result2 result2 = 1;</code>
     */
    public int getResult2Count() {
      return result2_.size();
    }
    /**
     * <code>repeated .Result2 result2 = 1;</code>
     */
    public com.example.proto.Query2.Result2 getResult2(int index) {
      return result2_.get(index);
    }
    /**
     * <code>repeated .Result2 result2 = 1;</code>
     */
    public com.example.proto.Query2.Result2OrBuilder getResult2OrBuilder(
        int index) {
      return result2_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < result2_.size(); i++) {
        output.writeMessage(1, result2_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < result2_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, result2_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.Query2.Query2Response)) {
        return super.equals(obj);
      }
      com.example.proto.Query2.Query2Response other = (com.example.proto.Query2.Query2Response) obj;

      boolean result = true;
      result = result && getResult2List()
          .equals(other.getResult2List());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getResult2Count() > 0) {
        hash = (37 * hash) + RESULT2_FIELD_NUMBER;
        hash = (53 * hash) + getResult2List().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.Query2.Query2Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query2.Query2Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query2.Query2Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query2.Query2Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query2.Query2Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query2.Query2Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query2.Query2Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query2.Query2Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query2.Query2Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.Query2.Query2Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query2.Query2Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query2.Query2Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.Query2.Query2Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Query2Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Query2Response)
        com.example.proto.Query2.Query2ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.Query2.internal_static_Query2Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.Query2.internal_static_Query2Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.Query2.Query2Response.class, com.example.proto.Query2.Query2Response.Builder.class);
      }

      // Construct using com.example.proto.Query2.Query2Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResult2FieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (result2Builder_ == null) {
          result2_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          result2Builder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.Query2.internal_static_Query2Response_descriptor;
      }

      @java.lang.Override
      public com.example.proto.Query2.Query2Response getDefaultInstanceForType() {
        return com.example.proto.Query2.Query2Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.Query2.Query2Response build() {
        com.example.proto.Query2.Query2Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.Query2.Query2Response buildPartial() {
        com.example.proto.Query2.Query2Response result = new com.example.proto.Query2.Query2Response(this);
        int from_bitField0_ = bitField0_;
        if (result2Builder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            result2_ = java.util.Collections.unmodifiableList(result2_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.result2_ = result2_;
        } else {
          result.result2_ = result2Builder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.Query2.Query2Response) {
          return mergeFrom((com.example.proto.Query2.Query2Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.Query2.Query2Response other) {
        if (other == com.example.proto.Query2.Query2Response.getDefaultInstance()) return this;
        if (result2Builder_ == null) {
          if (!other.result2_.isEmpty()) {
            if (result2_.isEmpty()) {
              result2_ = other.result2_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResult2IsMutable();
              result2_.addAll(other.result2_);
            }
            onChanged();
          }
        } else {
          if (!other.result2_.isEmpty()) {
            if (result2Builder_.isEmpty()) {
              result2Builder_.dispose();
              result2Builder_ = null;
              result2_ = other.result2_;
              bitField0_ = (bitField0_ & ~0x00000001);
              result2Builder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResult2FieldBuilder() : null;
            } else {
              result2Builder_.addAllMessages(other.result2_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.Query2.Query2Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.Query2.Query2Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.proto.Query2.Result2> result2_ =
        java.util.Collections.emptyList();
      private void ensureResult2IsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          result2_ = new java.util.ArrayList<com.example.proto.Query2.Result2>(result2_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.proto.Query2.Result2, com.example.proto.Query2.Result2.Builder, com.example.proto.Query2.Result2OrBuilder> result2Builder_;

      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public java.util.List<com.example.proto.Query2.Result2> getResult2List() {
        if (result2Builder_ == null) {
          return java.util.Collections.unmodifiableList(result2_);
        } else {
          return result2Builder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public int getResult2Count() {
        if (result2Builder_ == null) {
          return result2_.size();
        } else {
          return result2Builder_.getCount();
        }
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public com.example.proto.Query2.Result2 getResult2(int index) {
        if (result2Builder_ == null) {
          return result2_.get(index);
        } else {
          return result2Builder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public Builder setResult2(
          int index, com.example.proto.Query2.Result2 value) {
        if (result2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResult2IsMutable();
          result2_.set(index, value);
          onChanged();
        } else {
          result2Builder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public Builder setResult2(
          int index, com.example.proto.Query2.Result2.Builder builderForValue) {
        if (result2Builder_ == null) {
          ensureResult2IsMutable();
          result2_.set(index, builderForValue.build());
          onChanged();
        } else {
          result2Builder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public Builder addResult2(com.example.proto.Query2.Result2 value) {
        if (result2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResult2IsMutable();
          result2_.add(value);
          onChanged();
        } else {
          result2Builder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public Builder addResult2(
          int index, com.example.proto.Query2.Result2 value) {
        if (result2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResult2IsMutable();
          result2_.add(index, value);
          onChanged();
        } else {
          result2Builder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public Builder addResult2(
          com.example.proto.Query2.Result2.Builder builderForValue) {
        if (result2Builder_ == null) {
          ensureResult2IsMutable();
          result2_.add(builderForValue.build());
          onChanged();
        } else {
          result2Builder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public Builder addResult2(
          int index, com.example.proto.Query2.Result2.Builder builderForValue) {
        if (result2Builder_ == null) {
          ensureResult2IsMutable();
          result2_.add(index, builderForValue.build());
          onChanged();
        } else {
          result2Builder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public Builder addAllResult2(
          java.lang.Iterable<? extends com.example.proto.Query2.Result2> values) {
        if (result2Builder_ == null) {
          ensureResult2IsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, result2_);
          onChanged();
        } else {
          result2Builder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public Builder clearResult2() {
        if (result2Builder_ == null) {
          result2_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          result2Builder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public Builder removeResult2(int index) {
        if (result2Builder_ == null) {
          ensureResult2IsMutable();
          result2_.remove(index);
          onChanged();
        } else {
          result2Builder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public com.example.proto.Query2.Result2.Builder getResult2Builder(
          int index) {
        return getResult2FieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public com.example.proto.Query2.Result2OrBuilder getResult2OrBuilder(
          int index) {
        if (result2Builder_ == null) {
          return result2_.get(index);  } else {
          return result2Builder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public java.util.List<? extends com.example.proto.Query2.Result2OrBuilder> 
           getResult2OrBuilderList() {
        if (result2Builder_ != null) {
          return result2Builder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(result2_);
        }
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public com.example.proto.Query2.Result2.Builder addResult2Builder() {
        return getResult2FieldBuilder().addBuilder(
            com.example.proto.Query2.Result2.getDefaultInstance());
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public com.example.proto.Query2.Result2.Builder addResult2Builder(
          int index) {
        return getResult2FieldBuilder().addBuilder(
            index, com.example.proto.Query2.Result2.getDefaultInstance());
      }
      /**
       * <code>repeated .Result2 result2 = 1;</code>
       */
      public java.util.List<com.example.proto.Query2.Result2.Builder> 
           getResult2BuilderList() {
        return getResult2FieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.proto.Query2.Result2, com.example.proto.Query2.Result2.Builder, com.example.proto.Query2.Result2OrBuilder> 
          getResult2FieldBuilder() {
        if (result2Builder_ == null) {
          result2Builder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.proto.Query2.Result2, com.example.proto.Query2.Result2.Builder, com.example.proto.Query2.Result2OrBuilder>(
                  result2_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          result2_ = null;
        }
        return result2Builder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Query2Response)
    }

    // @@protoc_insertion_point(class_scope:Query2Response)
    private static final com.example.proto.Query2.Query2Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.Query2.Query2Response();
    }

    public static com.example.proto.Query2.Query2Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Query2Response>
        PARSER = new com.google.protobuf.AbstractParser<Query2Response>() {
      @java.lang.Override
      public Query2Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Query2Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Query2Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Query2Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.Query2.Query2Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Result2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Result2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string Year = 1;</code>
     */
    java.lang.String getYear();
    /**
     * <code>string Year = 1;</code>
     */
    com.google.protobuf.ByteString
        getYearBytes();

    /**
     * <code>string State = 2;</code>
     */
    java.lang.String getState();
    /**
     * <code>string State = 2;</code>
     */
    com.google.protobuf.ByteString
        getStateBytes();

    /**
     * <code>string Type = 3;</code>
     */
    java.lang.String getType();
    /**
     * <code>string Type = 3;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string Length = 4;</code>
     */
    java.lang.String getLength();
    /**
     * <code>string Length = 4;</code>
     */
    com.google.protobuf.ByteString
        getLengthBytes();

    /**
     * <code>double Expense = 5;</code>
     */
    double getExpense();
  }
  /**
   * Protobuf type {@code Result2}
   */
  public  static final class Result2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Result2)
      Result2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Result2.newBuilder() to construct.
    private Result2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Result2() {
      year_ = "";
      state_ = "";
      type_ = "";
      length_ = "";
      expense_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Result2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              year_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              state_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              length_ = s;
              break;
            }
            case 41: {

              expense_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.Query2.internal_static_Result2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.Query2.internal_static_Result2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.Query2.Result2.class, com.example.proto.Query2.Result2.Builder.class);
    }

    public static final int YEAR_FIELD_NUMBER = 1;
    private volatile java.lang.Object year_;
    /**
     * <code>string Year = 1;</code>
     */
    public java.lang.String getYear() {
      java.lang.Object ref = year_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        year_ = s;
        return s;
      }
    }
    /**
     * <code>string Year = 1;</code>
     */
    public com.google.protobuf.ByteString
        getYearBytes() {
      java.lang.Object ref = year_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        year_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private volatile java.lang.Object state_;
    /**
     * <code>string State = 2;</code>
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        state_ = s;
        return s;
      }
    }
    /**
     * <code>string State = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object type_;
    /**
     * <code>string Type = 3;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string Type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LENGTH_FIELD_NUMBER = 4;
    private volatile java.lang.Object length_;
    /**
     * <code>string Length = 4;</code>
     */
    public java.lang.String getLength() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        length_ = s;
        return s;
      }
    }
    /**
     * <code>string Length = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLengthBytes() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        length_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPENSE_FIELD_NUMBER = 5;
    private double expense_;
    /**
     * <code>double Expense = 5;</code>
     */
    public double getExpense() {
      return expense_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getYearBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, year_);
      }
      if (!getStateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, state_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
      }
      if (!getLengthBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, length_);
      }
      if (expense_ != 0D) {
        output.writeDouble(5, expense_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getYearBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, year_);
      }
      if (!getStateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, state_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
      }
      if (!getLengthBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, length_);
      }
      if (expense_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, expense_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.Query2.Result2)) {
        return super.equals(obj);
      }
      com.example.proto.Query2.Result2 other = (com.example.proto.Query2.Result2) obj;

      boolean result = true;
      result = result && getYear()
          .equals(other.getYear());
      result = result && getState()
          .equals(other.getState());
      result = result && getType()
          .equals(other.getType());
      result = result && getLength()
          .equals(other.getLength());
      result = result && (
          java.lang.Double.doubleToLongBits(getExpense())
          == java.lang.Double.doubleToLongBits(
              other.getExpense()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength().hashCode();
      hash = (37 * hash) + EXPENSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getExpense()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.Query2.Result2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query2.Result2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query2.Result2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query2.Result2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query2.Result2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Query2.Result2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Query2.Result2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query2.Result2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query2.Result2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.Query2.Result2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Query2.Result2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Query2.Result2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.Query2.Result2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Result2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Result2)
        com.example.proto.Query2.Result2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.Query2.internal_static_Result2_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.Query2.internal_static_Result2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.Query2.Result2.class, com.example.proto.Query2.Result2.Builder.class);
      }

      // Construct using com.example.proto.Query2.Result2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        year_ = "";

        state_ = "";

        type_ = "";

        length_ = "";

        expense_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.Query2.internal_static_Result2_descriptor;
      }

      @java.lang.Override
      public com.example.proto.Query2.Result2 getDefaultInstanceForType() {
        return com.example.proto.Query2.Result2.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.Query2.Result2 build() {
        com.example.proto.Query2.Result2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.Query2.Result2 buildPartial() {
        com.example.proto.Query2.Result2 result = new com.example.proto.Query2.Result2(this);
        result.year_ = year_;
        result.state_ = state_;
        result.type_ = type_;
        result.length_ = length_;
        result.expense_ = expense_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.Query2.Result2) {
          return mergeFrom((com.example.proto.Query2.Result2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.Query2.Result2 other) {
        if (other == com.example.proto.Query2.Result2.getDefaultInstance()) return this;
        if (!other.getYear().isEmpty()) {
          year_ = other.year_;
          onChanged();
        }
        if (!other.getState().isEmpty()) {
          state_ = other.state_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getLength().isEmpty()) {
          length_ = other.length_;
          onChanged();
        }
        if (other.getExpense() != 0D) {
          setExpense(other.getExpense());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.Query2.Result2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.Query2.Result2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object year_ = "";
      /**
       * <code>string Year = 1;</code>
       */
      public java.lang.String getYear() {
        java.lang.Object ref = year_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          year_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Year = 1;</code>
       */
      public com.google.protobuf.ByteString
          getYearBytes() {
        java.lang.Object ref = year_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          year_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Year = 1;</code>
       */
      public Builder setYear(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Year = 1;</code>
       */
      public Builder clearYear() {
        
        year_ = getDefaultInstance().getYear();
        onChanged();
        return this;
      }
      /**
       * <code>string Year = 1;</code>
       */
      public Builder setYearBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        year_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object state_ = "";
      /**
       * <code>string State = 2;</code>
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string State = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string State = 2;</code>
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string State = 2;</code>
       */
      public Builder clearState() {
        
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>string State = 2;</code>
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        state_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string Type = 3;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Type = 3;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string Type = 3;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object length_ = "";
      /**
       * <code>string Length = 4;</code>
       */
      public java.lang.String getLength() {
        java.lang.Object ref = length_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          length_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Length = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLengthBytes() {
        java.lang.Object ref = length_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          length_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Length = 4;</code>
       */
      public Builder setLength(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Length = 4;</code>
       */
      public Builder clearLength() {
        
        length_ = getDefaultInstance().getLength();
        onChanged();
        return this;
      }
      /**
       * <code>string Length = 4;</code>
       */
      public Builder setLengthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        length_ = value;
        onChanged();
        return this;
      }

      private double expense_ ;
      /**
       * <code>double Expense = 5;</code>
       */
      public double getExpense() {
        return expense_;
      }
      /**
       * <code>double Expense = 5;</code>
       */
      public Builder setExpense(double value) {
        
        expense_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double Expense = 5;</code>
       */
      public Builder clearExpense() {
        
        expense_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Result2)
    }

    // @@protoc_insertion_point(class_scope:Result2)
    private static final com.example.proto.Query2.Result2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.Query2.Result2();
    }

    public static com.example.proto.Query2.Result2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Result2>
        PARSER = new com.google.protobuf.AbstractParser<Result2>() {
      @java.lang.Override
      public Result2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Result2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Result2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Result2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.Query2.Result2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Query2Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Query2Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Query2Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Query2Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Result2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Result2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Query2.proto\";\n\rQuery2Request\022\014\n\004year\030" +
      "\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\016\n\006length\030\003 \001(\t\"+\n\016Q" +
      "uery2Response\022\031\n\007result2\030\001 \003(\0132\010.Result2" +
      "\"U\n\007Result2\022\014\n\004Year\030\001 \001(\t\022\r\n\005State\030\002 \001(\t" +
      "\022\014\n\004Type\030\003 \001(\t\022\016\n\006Length\030\004 \001(\t\022\017\n\007Expens" +
      "e\030\005 \001(\0012:\n\rQuery2Service\022)\n\006Query2\022\016.Que" +
      "ry2Request\032\017.Query2ResponseB\023\n\021com.examp" +
      "le.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Query2Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Query2Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Query2Request_descriptor,
        new java.lang.String[] { "Year", "Type", "Length", });
    internal_static_Query2Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Query2Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Query2Response_descriptor,
        new java.lang.String[] { "Result2", });
    internal_static_Result2_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Result2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Result2_descriptor,
        new java.lang.String[] { "Year", "State", "Type", "Length", "Expense", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
